version: '3.9'

services:
  golang_app:
    working_dir: /app
    build:
      dockerfile: dev.Dockerfile
      context: .
    environment:
      APP_ENV: development
      COOKIE_SECRET: b262e3681420222898e616c9
      DATABASE_DSN: 'host=golang_database user=admin password=password dbname=postgres port=5432 sslmode=disable TimeZone=Europe/Warsaw'
      JWT_SECRET: g2o9p48giynt21opv2uingpo4gn2o
      PORT: 9616 # This is a random port so as to distinguish it from the one available on the host.
    ports:
      - 9000:9616
    volumes:
      - ./:/app

  golang_database:
    image: library/postgres:14.4-alpine3.16
    shm_size: 2gb
    ports:
      - 9001:5432
    volumes:
      - type: volume
        source: golang_database_volume
        target: /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  golang_database_volume: