version: '3.9'

services:
  golang_app:
    working_dir: /app
    build:
      dockerfile: dev.Dockerfile
      context: .
    environment:
      APP_ENV: development
      DATABASE_DSN: 'host=golang_database user=admin password=password dbname=postgres port=5432 sslmode=disable TimeZone=Europe/Warsaw'
    ports:
      - 9000:8080
    volumes:
      - ./:/app

  golang_database:
    image: library/postgres:14.4-alpine3.16
    shm_size: 2gb
    ports:
      - 9001:5432
    volumes:
      - type: volume
        source: golang_database_volume
        target: /var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  golang_database_volume: